config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :restaurants, only: %i[index show new create]

  resources :restaurants do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  CATEGORIES = %w(chinese italian japanese french belgian)
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: CATEGORIES }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: 0..5

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  # GET /restaurants
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to restaurant_path(@restaurant), notice: 'Restaurant was successfully added'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # def destroy
  #   @review = Review.find(params[:id])
  #   @review.destroy
  #   redirect_to restaurant_path(@review.restaurant), status: :see_other
  # end

  private

  def review_params
    params.require(:review).permit(:content)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1>All restaurants</h1>
      <ul class="list-group mb-3">
        <% @restaurants.each do |restaurant| %>
          <li class="list-group-item">
            <%= link_to restaurant.name, restaurant_path(restaurant) %>
          </li>
        <% end %>
      </ul>
      <%= link_to "Add a new Restaurant", new_restaurant_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1>Create a new restaurant</h1>
      <%= simple_form_for @restaurant do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :phone_number %>
        <%= f.input :category, collection: Restaurant::CATEGORIES %>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1><%= @restaurant.name %></h1>
      <table class="table table-bordered">
        <tbody>
          <tr>
            <th scope="row">Address</th>
            <td><%= @restaurant.address %></td>
          </tr>
          <tr>
            <th scope="row">Phone Number</th>
            <td><%= @restaurant.phone_number %></td>
          </tr>
          <tr>
            <th scope="row">Category</th>
            <td><%= @restaurant.category %></td>
          </tr>
        </tbody>
      </table>

      <div class="list-group">
        <% @restaurant.reviews.each do |review| %>
          <li class="list-group-item">
            <small>
              <% count = 0 %>
              <% 5.times do %>
                <% if review.rating > count %>
                  <i class="fa-solid fa-star"></i>
                <% else %>
                  <i class="fa-regular fa-star"></i>
                <% end %>
                <% count += 1 %>
              <% end %>
            </small>
            <p><%= review.content %></p>
          </li>
        <% end %>
      </div>

      <%= simple_form_for [@restaurant, @review] do |f| %>
        <%= f.input :rating, collection: 0..5 %>
        <%= f.input :content%>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
      <%= link_to "See all restaurants", restaurants_path %>
    </div>
  </div>
</div>

app/views/review/new.html.erb
<h2><%= "Add a review to #{@resteraunt.name}" %></h2>
<% render "form", restaurant: @restaurant, review: @review%>
<li><%= link_to "Back to Restaurant", restaurant_path(@restaurant) %></li>